# Docker Compose configuration for MariaDB and MQTT Broker

services:
  # MariaDB database
  mariadb:
    image: mariadb:latest
    container_name: parking_db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./shared/sql/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    networks:
      - parking_network

  # MQTT Broker 
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: parking_mqtt_broker
    restart: unless-stopped
    ports:
      - "8883:8883" #MQTTS  - # Standard MQTT port # 1883
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt-broker/passwordfile:/mosquitto/config/passwordfile
      - ./shared/ssl/ca:/mosquitto/ssl/ca
      - ./shared/ssl/broker:/mosquitto/ssl/broker
    networks:
      - parking_network



volumes:
  db_data:

networks:
  parking_network:
    driver: bridge