# PC-side configuration file
# pc-side\config\config.yaml
camera:
  source: 0
  width: 640
  height: 480

database:
  host: "localhost"
  port: 3306
  user: "parking_user"
  password: "parking_password123"
  database: "parking_system"

mqtt:
  broker: "192.168.1.22"
  port: 8883
  client_id: "pc_camera"
  topics:
    parking_events: "parking/events"
    available_spots: "parking/available_spots"
  tls:  # Tilf√∏j TLS sektion
    ca_cert: "config/ssl/ca.crt"
    client_cert: "config/ssl/client.crt"
    client_key: "config/ssl/client.key"

license_plate:
  cascade_file: "config/cascade.xml"
  confidence_threshold: 0.8